// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfvurgedyqqokptecqbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmdnVyZ2VkeXFxb2twdGVjcWJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MTE5ODgsImV4cCI6MjA2NjE4Nzk4OH0.tDfQX8xoWKuIDhJAvJ_4rgQlVCWv5356wLWcg31o4I0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);